[package]
name = "rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hard_mode = { path = "hard_mode" }

[profile.release-with-debug]
inherits = "release"
debug = true